version: '2'
services:
  jhipsterlintestapplication-mongodb:
    image: mongo:4.2.3
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/jhipsterLinTestApplication/mongodb/:/data/db/
